/**
 * Compose the final reply: subject + body + cc list + disclosure banner.
 *
 * Voice rules (see docs/VOICE-GUIDE.md):
 *   - Chris's friendly, contraction-heavy tone
 *   - NEVER em dashes
 *   - For ai@ path: greeting + body + close + AI-Assistant signature
 *   - For chris_ooo path: AT-TOP disclosure banner is mandatory and unmissable
 *
 * Identity:
 *   - ai_alias  → From: Stratus AI Assistant <ai@>, signs as Stratus AI Assistant
 *   - chris_ooo → From: Chris Graves <chrisg@>, [Auto-reply via Stratus AI] subject prefix, top banner
 *
 * Marker token embedded in headers (X-Stratus-AI: v1) AND as an invisible HTML
 * comment for loop self-detection. Body still ends with a small "powered by"
 * line that includes the marker.
 */

const MARKER = "x-stratus-ai-msg-v1";

export function buildReply(env, ctx, handlerOutput) {
  const { envelope, path, classification, decision } = ctx;
  const isChrisPath = path === "chris_ooo";

  // Subject
  let subject = envelope.subject || "Following up";
  if (!/^re:/i.test(subject)) subject = "Re: " + subject;
  if (isChrisPath && !/\[auto-reply via stratus ai\]/i.test(subject)) {
    subject = `[Auto-reply via Stratus AI] ${subject}`;
  }

  // Body
  const greeting = greet(envelope.fromName, envelope.fromEmail);
  const banner = isChrisPath ? chrisOooBanner(env) : null;
  const bodyParts = [];
  if (banner) bodyParts.push(banner);
  if (greeting) bodyParts.push(greeting);
  for (const seg of handlerOutput.bodySegments || []) {
    if (seg) bodyParts.push(seg);
  }
  bodyParts.push(closing(env, isChrisPath, handlerOutput));
  bodyParts.push(signatureBlock(env, isChrisPath));
  bodyParts.push(disclosureFooter(env, isChrisPath));

  const bodyText = bodyParts.join("\n\n");
  const bodyHtml = bodyText
    .split("\n\n")
    .map(p => `<p>${escapeHtml(p).replace(/\n/g, "<br>")}</p>`)
    .join("\n")
    + `\n<!-- ${MARKER} -->`;

  // CC
  const cc = [];
  if (handlerOutput.extraCcJay && env.JAY_FLORENDO_EMAIL) {
    cc.push(env.JAY_FLORENDO_EMAIL);
  }
  if (isChrisPath && env.CHRIS_EMAIL) {
    // BCC Chris on every OOO mode reply so he can see what was sent
    // (handled via BCC, not CC, to avoid surprising customer)
  }

  return {
    subject,
    bodyText,
    bodyHtml,
    cc,
    bcc: isChrisPath ? [env.CHRIS_EMAIL] : [],
    threadId: envelope.gmailThreadId,
    inReplyTo: envelope.rfcMessageId,
    references: envelope.references,
    isDraft: Boolean(handlerOutput.isDraft) || env.SEND_MODE === "dry_run" || env.SEND_MODE === "draft_only",
    fromIdentity: isChrisPath
      ? { email: env.CHRIS_EMAIL, name: "Chris Graves" }
      : { email: env.AI_ALIAS_EMAIL, name: env.AI_DISPLAY_NAME || "Stratus AI Assistant" },
    marker: MARKER,
  };
}

function greet(name, email) {
  const first = (name || "").split(/[\s,]/)[0];
  if (first && /^[a-z][a-z'\-]+$/i.test(first)) {
    return `Hi ${first}!`;
  }
  return `Hi there!`;
}

function closing(_env, isChrisPath, _handlerOutput) {
  if (isChrisPath) return `Talk soon!`;
  return `Let me know what you think!`;
}

function signatureBlock(env, isChrisPath) {
  if (isChrisPath) {
    return [
      `Cheers,`,
      `Chris (out of office)`,
      `(reply was drafted by Stratus AI on Chris's behalf)`,
    ].join("\n");
  }
  return [
    `Cheers,`,
    env.AI_DISPLAY_NAME || `Stratus AI Assistant`,
    `Stratus Information Systems`,
    `${env.AI_ALIAS_EMAIL || "ai@stratusinfosystems.com"}`,
  ].join("\n");
}

function chrisOooBanner(env) {
  return [
    `>>> AUTO-REPLY FROM STRATUS AI <<<`,
    `Chris is out of office right now, so his AI assistant is replying on his behalf.`,
    `If this is urgent or you'd prefer a human, just reply "human please" and Jay Florendo (${env.JAY_FLORENDO_EMAIL || "jayf@stratusinfosystems.com"}) will pick it up.`,
    `Chris is BCC'd on every reply so he can review when he's back.`,
    `>>>`,
  ].join("\n");
}

function disclosureFooter(_env, isChrisPath) {
  if (isChrisPath) {
    return `_This reply was generated by Stratus AI on ${new Date().toLocaleDateString()}. Pricing and CRM data verified against live systems. Reply "human please" any time to route to Jay Florendo._`;
  }
  return `_I'm Stratus's AI Sales Assistant. I help with quote URLs, licensing FAQs, and order status while the team is busy. For anything contractual, financial, or complex, reply "human please" and Jay Florendo will pick it up._`;
}

function escapeHtml(s) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
