name = "stratus-ai-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
# Non-secret config (secrets set via `wrangler secret put`)
# WEBEX_BOT_TOKEN = set via wrangler secret
# ANTHROPIC_API_KEY = set via wrangler secret

[[kv_namespaces]]
binding = "CONVERSATION_KV"
id = "360fbb8a75bf400e87cb96893a811a56"

# Shared pricing KV — written by GChat worker's daily cron, read here for live prices
[[kv_namespaces]]
binding = "PRICES_KV"
id = "af24db17eaa644fe9456e2ae74379766"
